name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  typing:
    uses: ./.github/workflows/typing.yml

  security:
    uses: ./.github/workflows/security.yml