# Generated by Django 4.1.2 on 2022-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='other_models_2',
            field=models.ManyToManyField(to='app1.othermodel2'),
        ),
    ]
