# Generated by Django 4.1.2 on 2022-11-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_mymodel_other_models_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='other_model_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.othermodel1'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
