# Generated by Django 4.1.2 on 2022-11-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_mymodel_other_model_1_alter_mymodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='other_models_2',
            field=models.ManyToManyField(null=True, to='app1.othermodel2'),
        ),
    ]
