# Generated by Django 4.1.2 on 2022-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_mymodel_other_models_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='other_models_2',
            field=models.ManyToManyField(blank=True, to='app1.othermodel2'),
        ),
    ]
