# Generated by Django 4.1.2 on 2022-11-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_mymodel_other_models_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='other_model_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.othermodel1'),
        ),
    ]
