# Generated by Django 4.1.2 on 2022-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_mymodel_other_model_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='float_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
